encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry_page, name="entry_page"),
    path("search/", views.search_result, name="search_result"),
    path("create_new/", views.create_new, name="create_new"),
    path("edit_page/<str:entry_title>", views.edit_page, name="edit_page"),
    path("random", views.random, name="random"),

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from . import util
from markdown2 import Markdown
from django.urls import reverse

from random import randint
from django import forms
from django.http import HttpResponseRedirect
import re

markdowner = Markdown()

def get_lower_entries():
    '''Gets a list of entries lowers them and returns a lowered list'''

    lower_entries = []

    # get the entries
    entries = util.list_entries()

    # lowers each entries and appends them to the lower list
    for entry in entries:
        lower_entries.append(entry.lower())

    # returns the lowered list
    return lower_entries

def save_content(title, raw_content):
    '''Get a title and raw content, and saves the entry'''
    content = f"#{title}\n" + raw_content
    util.save_entry(title, content)

def index(request):
    '''Renders the home page'''

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry_page(request, entry):
    '''Renders a page of the encyclopedia entry'''

    # coverts the .md file format into HTML
    try:
        coverted = markdowner.convert(util.get_entry(entry))
        
    # if the entry is None renders a not found message
    except:
        return render(request, "encyclopedia/entry_page.html",{
        "entry_title": "Not found",
        "not_found": f"{entry.capitalize()} was not found"
    })

    # passing the entry_title and converted HTML code to the entry_page and renders it
    return render(request, "encyclopedia/entry_page.html",{
        "entry_title":entry.capitalize(),
        "entry": coverted
    })

def search_result(request):
    '''Takes a user input and return a page acordingly'''

    # if the form is submited the search_result page is returned
    if request.method == 'POST':

        # gets the user input and assigns it to query variable
        query = request.POST.get('q')

        # gets the entries
        entries = util.list_entries()
        
        # lower the entries
        lowered = get_lower_entries()

        # if the query is in the entries list returns the entry page
        if query.lower() in lowered:
            #  Redirects the user to the entries page
            return HttpResponseRedirect(reverse("encyclopedia:entry_page", args=[query]))

        else:
            # if the user query is a substring of an entry it returns the entry
            for entry in entries:
                if re.search(query, entry):

                    return render(request, "encyclopedia/search_result.html", {
                        "query": entry
                    })
            # if the query is not a substring returns a not found message
            return render(request, "encyclopedia/entry_page.html",{
                    "entry_title": "Not found",
                    "not_found": f"{query.capitalize()} was not found"
                })
        
def create_new(request):
    '''Let the user create a new encyclopedia entry'''

    if request.method == 'GET':

    # returns the create_new page
        return render(request,  "encyclopedia/create_new.html")
    
    else:
        # gets the entry title
        title = request.POST.get('entry_title')
        # gets the entry content
        raw_content = request.POST.get('entry_content')

        
        # checks if title and content field are filled
        if title and raw_content:
            # checks if the entry name already exists
            if title.lower() in get_lower_entries():
                # returns an error message
                return render(request, "encyclopedia/error.html",{
                    "message":"Sorry but the entry already exists",
                })
            
            # if the entry does not already exists it makes an .md file
            else:
                # saves the content
                save_content(title, raw_content)
            
            return HttpResponseRedirect(reverse("encyclopedia:index"))
        else:
            # returns an error message
            return render(request, "encyclopedia/error.html",{
                "message":"Sorry but the title or content field are empty",
            })

def edit_page(request, entry_title):
    '''Let the user to edit a entry content'''

    if request.method == "GET":
        # get the content of the entry
        raw_content = util.get_entry(entry_title)
        # get the lines of the content
        lines = raw_content.splitlines()
        # get rid of the firt line of the content
        content = "\n".join(lines[1:])

        return render(request,  "encyclopedia/edit_page.html",{
            "entry_title":entry_title,
            "content": content
        })
    else:

        # gets the entry title
        title = request.POST.get('edit_title')
        # gets the entry content
        raw_content = request.POST.get('edit_content')
        # saves the content
        save_content(title, raw_content)

        return HttpResponseRedirect(reverse("encyclopedia:index"))

def random(request):
    '''Redirect the user on a random entry page'''

    #get the number of entries
    entries = util.list_entries()

    # count the entries
    cnt_entries = len(entries)

    # return sa random entry
    rand_entry = entries[randint(0, cnt_entries - 1)]
    return HttpResponseRedirect(reverse("encyclopedia:entry_page", args=[rand_entry]))

encyclopedia/templates/encyclopedia/create_new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create new
{% endblock %}

{% block body %}
    <h1>Create new encyclopedia entry</h1>

    <form action="{% url 'encyclopedia:create_new' %}" method="post">
        {% csrf_token %}
        <input class="title_field" type="text" name="entry_title" placeholder="Entry title">
        <br>
        <label for="create_new">Content of the entry:</label>
        <br>
        <textarea name="entry_content"></textarea>
        <br>
        <input class="submit_btn" type="submit" value="Create entry">
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_title }} edit page
{% endblock %}

{% block body %}
    <form action="edit_page" method="post">
        {% csrf_token %}
        <input class="title_field" type="text" name="edit_title" value="{{ entry_title }}" placeholder="Entry title">
        <br>
        <label for="create_new">Content of the entry:</label>
        <br>
        <textarea name="edit_content">{{ content }}</textarea>
        <br>
        <div class ="submit_btn">
        <input class="submit_btn" type="submit" value="Edit entry">
    </form>  
{% endblock %}

encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_title }}
{% endblock %}

{% block body %}


    {% if not_found %}
<!-- If not_found not None renders the message -->
        <h1>{{ not_found }}</h1>
    {% else %}
<!-- Using the safe filter to render the HTML code from entry variable -->
        {{ entry | safe }}
        <div class="edit_wrapper">
        <a href="{% url 'encyclopedia:edit_page' entry_title %}" class="edit_btn submit_btn">Edit entry</a>
    </div>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>{{message}}</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <!-- link for every list element -->
            <li><a href="{% url 'encyclopedia:entry_page' entry %}">{{entry}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search_result' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search_result
{% endblock %}

{% block body %}
    <h1>Search results</h1>

    <ul>
        <!-- link for every list element -->
        <li><a href="{% url 'encyclopedia:entry_page' query %}">{{query}}</a></li>

    </ul>

{% endblock %}